project:
  type: website
  output-dir: docs

website:
  title: "Priyabrata Saha"
  navbar:
    logo: "assets/images/logo.png" 
    left: []      # Only the title on the left
    right:
      - text: Home
        href: index.qmd
      - text: Research
        href: research.qmd
      - text: Publications
        href: publications.qmd
  search: true
  google-analytics: G-8T03CZESVL

  page-footer:
    center: |
      © 2026 Priyabrata Saha ·
      Made with
      <a href="https://quarto.org" target="_blank" rel="noopener" class="footer-quarto">
        <img src="https://quarto.org/quarto.png" alt="Quarto" />
      </a>

format:
  html:
    theme:
      light:
        - cosmo
        - brand.scss
      dark:
        - cosmo
        - brand-dark.scss    
    grid:
      body-width: 800px
    include-in-header:
      text: |
        <link rel="preconnect" href="https://fonts.googleapis.com">
        <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
        <link href="https://fonts.googleapis.com/css2?family=Lato:wght@400;700&family=Libre+Baskerville:wght@400;700&display=swap" rel="stylesheet">
        <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.3/font/bootstrap-icons.css">
        <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/academicons/css/academicons.min.css">
    css:
      - styles.css
      - assets/listing-styles.css
      - assets/research.css
    toc: false
